export { default as Player } from "./Player.vue"
export { default as Sidebar } from "./Sidebar.vue"
export { default as Audio } from "./Audio.vue"
export { default as CurveIcon } from "./CurveIcon.vue"
export { default as Slide } from "./Slide.vue"